#none:
#	@echo -e "One - target one\nTwo - target two"
#
#One:
#	@echo one
#Two:
#	@echo two

help:
	@grep "####" Makefile | grep -v grep

One: #### target one
	@echo one

Two: #### target two
	@echo two