none:
	@echo -e "One - target one\nTwo - target two"

One:
	@echo one
Two:
	@echo two

help:
	@grep "####" Makefile | grep -v grep | sed -e "s/####//"

One: #### target one
	@echo one

Two: #### target two
	@echo two

# -v will not fetch that word means grep word will not fetched sed -e "s/####//" will be replaced


##tagets

##     rules
